name: Greenplum Client Tools Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # This enables manual triggering

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        # You can add more OS configurations if needed
        # os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create test directories
      run: |
        mkdir -p logs
        mkdir -p test_data

    - name: Run tests
      env:
        GPDB_HOST: ${{ secrets.GPDB_HOST }}
        GPDB_USERNAME: ${{ secrets.GPDB_USERNAME }}
        GPDB_PASSWORD: ${{ secrets.GPDB_PASSWORD }}
      run: |
        pytest -v tests/test_core_tools.py

    - name: Generate test report
      if: always()
      run: |
        pytest --html=report.html --self-contained-html tests/

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v2  # Changed to v2 to avoid potential issues
      with:
        name: test-report
        path: report.html

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2  # Changed to v2 to avoid potential issues
      with:
        name: test-logs
        path: logs/
