name: Greenplum Client Tools Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # This enables manual triggering

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Check Python version
      run: |
        python3 --version
        pip3 --version || echo "pip3 not found"

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Debug environment
      run: |
        ls -la
        echo "Content of tests directory:"
        ls -la tests/ || echo "tests directory not found"
        echo "Python version:"
        python3 --version
        echo "Installed packages:"
        python3 -m pip list
        
    - name: Check connectivity
      run: |
        nc -zv ${{ secrets.GPDB_HOST }} 22 || echo "Cannot reach SSH port"
        # Also check the Greenplum port if different
        # nc -zv ${{ secrets.GPDB_HOST }} 5432 || echo "Cannot reach Greenplum port"

    - name: Run tests
      env:
        GPDB_HOST: ${{ secrets.GPDB_HOST }}
        GPDB_USERNAME: ${{ secrets.GPDB_USERNAME }}
        GPDB_PASSWORD: ${{ secrets.GPDB_PASSWORD }}
      run: |
        pytest -v tests/test_core_tools.py || echo "Tests failed but continuing workflow"
